//@ui5-bundle com/myorg/myapp/Component-preload.js
sap.ui.require.preload({
	"com/myorg/myapp/Component.js":function(){
"use strict";sap.ui.define(["sap/ui/core/UIComponent","./model/models","sap/ui/Device"],function(t,e,s){function i(t){return t&&t.__esModule&&typeof t.default!=="undefined"?t.default:t}const n=i(e);const o=t.extend("com.myorg.myapp.Component",{metadata:{manifest:"json"},init:function e(){t.prototype.init.call(this);this.setModel(n.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function t(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!s.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}});return o});
},
	"com/myorg/myapp/controller/App.controller.js":function(){
"use strict";sap.ui.define(["./BaseController"],function(e){function t(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}const n=t(e);const o=n.extend("com.myorg.myapp.controller.App",{onInit:function e(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}});return o});
},
	"com/myorg/myapp/controller/BaseController.js":function(){
"use strict";sap.ui.define(["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){const o=e.extend("com.myorg.myapp.controller.BaseController",{getOwnerComponent:function t(){return e.prototype.getOwnerComponent.call(this)},getRouter:function e(){return t.getRouterFor(this)},getResourceBundle:function e(){const t=this.getOwnerComponent().getModel("i18n");return t.getResourceBundle()},getModel:function e(t){return this.getView().getModel(t)},setModel:function e(t,n){this.getView().setModel(t,n);return this},navTo:function e(t,n,o){this.getRouter().navTo(t,n,undefined,o)},onNavBack:function e(){const t=n.getInstance().getPreviousHash();if(t!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}});return o});
},
	"com/myorg/myapp/controller/Main.controller.js":function(){
"use strict";sap.ui.define(["./BaseController","sap/ui/model/json/JSONModel","nominatim-client","sap/m/MessageBox"],function(e,t,n,a){function o(e){return e&&e.__esModule&&typeof e.default!=="undefined"?e.default:e}const i=o(e);const l=i.extend("com.myorg.myapp.controller.Main",{onInit:function e(){const n=new t;this.setModel(n);void this.loadWeatherData()},loadWeatherData:async function e(){let t=arguments.length>0&&arguments[0]!==undefined?arguments[0]:"49.31";let n=arguments.length>1&&arguments[1]!==undefined?arguments[1]:"8.64";let a=arguments.length>2&&arguments[2]!==undefined?arguments[2]:"Walldorf";const o=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${t}&longitude=${n}&current_weather=true`);const i=await o.json();i.placeName=a;this.getModel().setData(i)},locationChange:function e(t){const o=t.getParameters().value;n.createClient({useragent:"UI5 TypeScript Tutorial App",referer:"https://localhost"}).search({q:o}).then(e=>{if(e.length>0){return this.loadWeatherData(e[0].lat,e[0].lon,e[0].display_name)}else{a.alert(`Location ${o} not found`,{actions:a.Action.CLOSE})}}).catch(()=>{a.alert(`Failure while searching ${o}`,{actions:a.Action.CLOSE})})}});return l});
},
	"com/myorg/myapp/i18n/i18n.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Say Hello\n',
	"com/myorg/myapp/i18n/i18n_de.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Sag Hallo\n',
	"com/myorg/myapp/i18n/i18n_en.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Say Hello\n',
	"com/myorg/myapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.myorg.myapp","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.myorg.myapp.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.115.1","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.myorg.myapp.i18n.i18n"}}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.myorg.myapp.view","controlId":"app","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"com/myorg/myapp/model/formatter.js":function(){
"use strict";sap.ui.define([],function(){var e={formatValue:e=>e===null||e===void 0?void 0:e.toUpperCase()};return e});
},
	"com/myorg/myapp/model/models.js":function(){
"use strict";sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,i,n){var d={createDeviceModel:()=>{const d=new e(n);d.setDefaultBindingMode(i.OneWay);return d}};return d});
},
	"com/myorg/myapp/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.myorg.myapp.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"><App id="app" /></mvc:View>\n',
	"com/myorg/myapp/view/Main.view.xml":'<mvc:View\n\tcontrollerName="com.myorg.myapp.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"\n\txmlns:form="sap.ui.layout.form"\n\tcore:require="{\n\t\tformatter: \'com/myorg/myapp/model/formatter\'\n\t}"><Page id="page" title="Current Weather"><content><Input change=".locationChange" placeholder="Enter Location" /><form:SimpleForm><Label text="Place" /><Text text="{/placeName}" /><Label text="Temperature" /><Text text="{/current_weather/temperature} °C" /><Label text="Wind Speed" /><Text text="{/current_weather/windspeed} km/h" /><Label text="Wind Direction" /><Text text="{/current_weather/winddirection} °" /></form:SimpleForm><FormattedText class="sapUiResponsiveMargin" htmlText="&lt;a href=\'https://open-meteo.com/\'&gt;Weather data by Open-Meteo.com&lt;/a&gt; under &lt;a href=\'https://creativecommons.org/licenses/by/4.0/\'&gt;Attribution 4.0 International (CC BY 4.0)&lt;/a&gt; license" /></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
